#!/usr/bin/env node
/**
 * OMIKAMI WALLET — Content-Security-Policy generator (Gate 7).
 *
 * A Next.js static export ships a handful of INLINE hydration scripts
 * (`self.__next_f.push(...)`). A strict `script-src 'self'` would block them and
 * break the app, and a static export cannot use per-request nonces. So we take
 * the robust path: hash every inline <script> in the export (SHA-256, the CSP
 * hash form) and allow exactly those hashes — nothing else inline runs.
 *
 * Output: `apps/web/out/_headers` (Cloudflare Pages / Netlify format) with the
 * CSP plus a hardened set of security headers. See SECURITY_HEADERS.md for the
 * per-host variants (netlify.toml, IPFS <meta>) and the custom-RPC trade-off.
 *
 * Run AFTER `pnpm build`. Idempotent.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'apps/web/out';

/**
 * Runtime connect targets (fetch/XHR). These are the ONLY hosts the running app
 * contacts, matching PRIVACY.md and the bundle allowlist:
 *   - Sepolia default RPC (block probe, balances, logs, allowances)
 *   - Ethereum mainnet default RPC (only if the wallet is on mainnet)
 * A user-configured custom RPC endpoint is NOT covered here on purpose — see
 * SECURITY_HEADERS.md "Custom RPC endpoints" before enabling that in production.
 */
const CONNECT_SRC = ["'self'", 'https://11155111.rpc.thirdweb.com', 'https://eth.merkle.io'];

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (name.endsWith('.html')) acc.push(p);
  }
  return acc;
}

function inlineScriptHashes(htmlFiles) {
  const hashes = new Set();
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  for (const file of htmlFiles) {
    const html = readFileSync(file, 'utf8');
    let m;
    while ((m = re.exec(html)) !== null) {
      const attrs = m[1] ?? '';
      const body = m[2] ?? '';
      if (/\bsrc\s*=/.test(attrs)) continue; // external script: covered by 'self'
      if (body.trim().length === 0) continue;
      const digest = createHash('sha256').update(body, 'utf8').digest('base64');
      hashes.add(`'sha256-${digest}'`);
    }
  }
  return [...hashes].sort();
}

const htmlFiles = walk(OUT);
if (htmlFiles.length === 0) {
  console.error(`generate-csp: no HTML in ${OUT}. Run "pnpm build" first.`);
  process.exit(1);
}

const scriptHashes = inlineScriptHashes(htmlFiles);

const csp = [
  "default-src 'none'",
  // Inline hydration scripts are allowed ONLY by their exact hash.
  `script-src 'self' ${scriptHashes.join(' ')}`,
  // Styles: same-origin stylesheet + inline style tags Next emits. Inline
  // styles are far lower risk than scripts; tighten to hashes later if desired.
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src ${CONNECT_SRC.join(' ')}`,
  "manifest-src 'self'",
  "worker-src 'self'",
  "frame-src 'none'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "form-action 'none'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

const headersBlock = `# GENERATED by scripts/generate-csp.mjs — do not edit by hand.
# Regenerate after every build: pnpm build && pnpm csp
# Inline-script hashes: ${scriptHashes.length}

/*
  Content-Security-Policy: ${csp}
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Cross-Origin-Embedder-Policy: require-corp
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
`;

const outFile = join(OUT, '_headers');
writeFileSync(outFile, headersBlock, 'utf8');
console.log(
  `generate-csp: wrote ${outFile} (${scriptHashes.length} inline-script hashes, ${htmlFiles.length} HTML files).`,
);
